runtime: php73

handlers:
  - url: /
    static_dir: public

env_variables:
  APP_KEY: base64:z5GyN233uvuJOrZjEgmORgYG1IRTUBuRSp71rj9Y+vI=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  #CACHE_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: scholarships
  DB_USERNAME: root
  DB_PASSWORD: coep@123
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/scholarships-270714:us-east1:scholarship"
  ## for PostgreSQL, use DB_HOST:
  # DB_HOST: "/cloudsql/YOUR_CONNECTION_NAME"
  